version: '3'
services:
    express_server:
        build: .
        container_name: "express_server"
        environment:
            - NODE_ENV=devasd
        volumes:
            - .:/app
        ports:
            - 8080:8080
        command: yarn start-dev
        links:
            - mongo
    mongo:
        image: mongo:latest
        container_name: "mongodb"
        environment:
          - MONGO_DATA_DIR=/data/db
        volumes:
          - data-volume:/data/db
        ports:
            - 27017:27017
volumes:
    data-volume: